import type { KnipConfig } from "knip";

type Workspace = NonNullable<KnipConfig["workspaces"]>[string];

// The yak-swc wasm plugin is referenced by name so knip cannot see it
const yakSwc = ["yak-swc"];

// Every index file in the e2e tests is an entry and imports that only resolve after copying to `.tmp/` are expected
const bundler = (extra: Workspace = {}): Workspace => ({
  entry: ["**/*.{ts,tsx,mjs}"],
  ignoreUnresolved: [/\/cases\/\[case-name\]\/index\.tsx$/],
  ...extra,
});

const config: KnipConfig = {
  // Exports that are also used inside their own module are a deliberate choice
  ignoreExportsUsedInFile: true,
  // System binary used by the e2e runner
  ignoreBinaries: ["pgrep"],
  workspaces: {
    "packages/next-yak": {
      entry: ["runtime/__tests__/*.tsx"],
      // Used by the yak-internals code that tsdown bundles into this package
      ignoreDependencies: ["@babel/parser", ...yakSwc],
    },
    "packages/yak-solid": {
      entry: ["runtime/__tests__/*.tsx"],
      ignoreDependencies: [
        "@babel/parser",
        ...yakSwc,
        // vite-plugin-solid registers `@testing-library/jest-dom/vitest` as a
        // vitest setup file whenever the package is installed.
        "@testing-library/jest-dom",
      ],
    },
    "packages/yak-swc": {
      // Rust fixture inputs/snapshots for the SWC plugin tests
      ignore: ["yak_swc/tests/fixture/**"],
      // Required by swc for published wasm plugins, never imported
      ignoreDependencies: ["@swc/counter"],
    },
    "packages/yak-internals": {
      ignore: ["isolated-source-eval/__tests__/fixtures/**"],
    },
    "packages/eslint-plugin-yak": {
      ignore: ["rules/fixtures/**"],
    },
    "packages/storybook-addon-yak": {
      ignoreDependencies: yakSwc,
    },
    docs: {
      // Fumadocs convention file
      entry: ["mdx-components.tsx"],
      ignore: [
        // Vendored type definitions served to the playground
        "public/**",
        // wasm-pack output.
        "playground-wasm/out/**",
      ],
      // Referenced by name in the webpack rule in next.config.mjs
      ignoreDependencies: ["raw-loader", ...yakSwc],
    },
    // yak.context.ts is picked up by convention by the yak loaders (see yak-internals/config.ts)
    "examples/next-js": { entry: ["yak.context.ts"], ignoreDependencies: yakSwc },
    "examples/rsbuild": { entry: ["src/index.tsx"] },
    "examples/storybook": {
      entry: ["yak.context.ts", ".storybook-webpack/**/*.{ts,tsx}"],
      ignoreDependencies: yakSwc,
      storybook: { config: [".storybook/main.ts", ".storybook-webpack/main.ts"] },
    },
    "examples/tanstack-start": { entry: ["yak.context.ts"] },
    "examples/vite": { entry: ["yak.context.ts"] },
    "examples/vite-solid": { entry: ["yak.context.ts"] },
    e2e: {
      // Copied into each bundler's `.tmp/` next to its playwright.config.ts
      entry: ["playwright-base.ts"],
      // Mounted into the bundler scaffolds at runtime
      ignore: ["cases/**"],
      // Type-check the cases (tsconfig.json), not imported by the runner
      ignoreDependencies: ["next-yak", "@types/react"],
    },
    "e2e/bundlers/next-app-turbopack": bundler({ ignoreDependencies: yakSwc }),
    "e2e/bundlers/next-app-webpack": bundler({ ignoreDependencies: yakSwc }),
    "e2e/bundlers/next-pages-turbopack": bundler({ ignoreDependencies: yakSwc }),
    "e2e/bundlers/next-pages-webpack": bundler({ ignoreDependencies: yakSwc }),
    "e2e/bundlers/rsbuild": bundler(),
    "e2e/bundlers/tanstack-start-rsbuild": bundler({
      // Generated by the TanStack router plugin at build time
      ignoreUnresolved: [/\/cases\/\[case-name\]\/index\.tsx$/, "./routeTree.gen.ts"],
    }),
    "e2e/bundlers/vinext-pages": bundler(),
    "e2e/bundlers/vite": bundler(),
    "e2e/bundlers/vite-solid": bundler(),
  },
};

export default config;
