packages:
  - packages/*
catalogs:
  core:
    "@babel/core": 7.26.10
    "@babel/plugin-syntax-typescript": 7.25.9
    "@swc/counter": 0.1.3

  dev:
    "@babel/preset-typescript": 7.27.0
    "@babel/types": 7.27.0
    "@changesets/cli": 2.29.2
    "@codspeed/benchmark.js-plugin": 4.0.1
    "@monaco-editor/react": 4.7.0
    "@next/mdx": 15.3.1
    "@shikijs/monaco": 3.3.0
    "@shikijs/transformers": 3.3.0
    "@swc/core": 1.11.22
    "@tailwindcss/postcss": 4.1.4
    "@testing-library/dom": 10.4.0
    "@testing-library/jest-dom": 6.6.3
    "@testing-library/react": 16.3.0
    "@types/babel__core": 7.20.5
    "@types/benchmark": 2.1.5
    "@types/jest": 29.5.14
    "@types/mdx": 2.0.13
    "@types/node": 22.15.2
    "@types/react": 19.1.2
    "@types/react-dom": 19.1.2
    "@types/webpack": 5.28.5
    "@vitejs/plugin-react": 4.4.1
    autoprefixer: 10.4.21
    benchmark: 2.1.4
    fast-glob: 3.3.3
    fumadocs-core: 15.2.11
    fumadocs-mdx: 11.6.1
    fumadocs-twoslash: 3.1.1
    fumadocs-ui: 15.2.11
    jest: 29.7.0
    jest-environment-jsdom: 29.7.0
    jsdom: 26.1.0
    memfs: 4.17.0
    next: 15.3.1
    next-themes: 0.4.6
    postcss: 8.5.3
    postcss-nested: 7.0.2
    prettier: 3.5.3
    raw-loader: 4.0.2
    react: 19.1.0
    react-dom: 19.1.0
    react-resizable-panels: 2.1.8
    shiki: 3.3.0
    shiki-magic-move: 1.1.0
    styled-components: 6.1.17
    swc-loader: 0.2.6
    tailwindcss: 4.1.4
    tree-kill: 1.2.2
    tsup: 8.4.0
    typescript: 5.8.3
    unionfs: 4.5.4
    vite: 6.3.3
    vitest: 3.1.2
    webpack: 5.99.7
