packages:
  - packages/*

catalogs:
  core:
    "@babel/parser": ^7.26.0
    "@babel/traverse": ^7.26.0
    "@swc/counter": 0.1.3
  dev:
    "@babel/preset-typescript": 7.27.1
    "@changesets/cli": 2.29.6
    "@codspeed/benchmark.js-plugin": 4.0.1
    "@eslint/eslintrc": 3.3.1
    "@monaco-editor/react": 4.7.0
    "@next/eslint-plugin-next": 15.5.2
    "@next/mdx": 15.5.2
    "@radix-ui/react-switch": 1.2.6
    "@shikijs/monaco": 3.12.0
    "@shikijs/transformers": 3.12.0
    "@swc/core": 1.13.5
    "@tailwindcss/postcss": 4.1.12
    "@testing-library/dom": 10.4.1
    "@testing-library/jest-dom": 6.8.0
    "@testing-library/react": 16.3.0
    "@types/babel__core": 7.20.5
    "@types/babel__traverse": 7.28.0
    "@types/benchmark": 2.1.5
    "@types/jest": 30.0.0
    "@types/mdx": 2.0.13
    "@types/node": 24.3.0
    "@types/react": 19.1.12
    "@types/react-dom": 19.1.9
    "@types/webpack": 5.28.5
    "@typescript-eslint/rule-tester": 8.41.0
    "@typescript-eslint/utils": 8.41.0
    "@vitejs/plugin-react": 5.0.2
    autoprefixer: 10.4.21
    benchmark: 2.1.4
    eslint: 9.34.0
    eslint-config-next: 15.5.2
    eslint-doc-generator: 2.2.2
    fast-glob: 3.3.3
    fflate: 0.8.2
    fumadocs-core: 15.7.6
    fumadocs-mdx: 11.8.1
    fumadocs-twoslash: 3.1.7
    fumadocs-ui: 15.7.6
    jest: 30.1.1
    jest-environment-jsdom: 30.1.1
    js-base64: 3.7.8
    jsdom: 26.1.0
    lz-string: 1.5.0
    memfs: 4.38.2
    next: 15.5.2
    next-themes: 0.4.6
    postcss: 8.5.6
    postcss-nested: 7.0.2
    prettier: 3.6.2
    raw-loader: 4.0.2
    react: 19.1.1
    react-dom: 19.1.1
    react-resizable-panels: 3.0.5
    shiki: 3.12.0
    shiki-magic-move: 1.1.0
    styled-components: 6.1.19
    swc-loader: 0.2.6
    tailwindcss: 4.1.12
    tree-kill: 1.2.2
    tsup: 8.5.0
    typescript: 5.9.2
    unionfs: 4.6.0
    vite: 7.1.3
    vitest: 3.2.4
    wasm-pack: 0.13.1
    webpack: 5.101.3
