packages:
  - packages/*
  - examples/*
  - benchmarks
  - cross-file-tests
  - docs
  - e2e
  - e2e/bundlers/*

catalogs:
  core:
    "@babel/parser": ^7.28.5
    "@babel/traverse": ^7.28.5
    "@swc/core": 1.15.5
    "@swc/counter": 0.1.3
  dev:
    "@babel/preset-typescript": 7.28.5
    "@changesets/cli": 2.29.7
    "@codspeed/benchmark.js-plugin": 5.0.1
    "@eslint/eslintrc": 3.3.1
    "@monaco-editor/react": 4.7.0
    "@next/eslint-plugin-next": 16.1.1
    "@next/mdx": 16.1.1
    "@radix-ui/react-switch": 1.2.6
    "@shikijs/monaco": 3.20.0
    "@shikijs/transformers": 3.20.0
    "@storybook/addon-docs": 10.1.11
    "@storybook/addon-webpack5-compiler-swc": 4.0.2
    "@storybook/react": 10.1.11
    "@storybook/react-vite": 10.1.11
    "@storybook/react-webpack5": 10.1.11
    "@swc/helpers": 0.5.17
    "@tailwindcss/postcss": 4.1.16
    "@testing-library/dom": 10.4.1
    "@testing-library/jest-dom": 6.9.1
    "@testing-library/react": 16.3.0
    "@types/babel__core": 7.20.5
    "@types/babel__traverse": 7.28.0
    "@types/benchmark": 2.1.5
    "@types/jest": 30.0.0
    "@types/mdx": 2.0.13
    "@types/node": 24.9.2
    "@types/react": 19.2.7
    "@types/react-dom": 19.2.3
    "@types/webpack": 5.28.5
    "@typescript-eslint/rule-tester": 8.46.2
    "@typescript-eslint/utils": 8.46.2
    "@vitejs/plugin-react": 5.1.0
    "@vitejs/plugin-react-swc": 4.2.0
    autoprefixer: 10.4.21
    benchmark: 2.1.4
    eslint: 9.38.0
    eslint-config-next: 16.0.4
    eslint-doc-generator: 2.3.0
    fast-glob: 3.3.3
    fflate: 0.8.2
    fumadocs-core: 16.0.5
    fumadocs-mdx: 13.0.2
    fumadocs-twoslash: 3.1.9
    fumadocs-ui: 16.0.5
    jest: 30.2.0
    jest-environment-jsdom: 30.2.0
    js-base64: 3.7.8
    jsdom: 27.0.1
    lz-string: 1.5.0
    memfs: 4.50.0
    next: 16.1.1
    next-themes: 0.4.6
    postcss: 8.5.6
    postcss-nested: 7.0.2
    prettier: 3.6.2
    raw-loader: 4.0.2
    react: 19.2.3
    react-dom: 19.2.3
    react-resizable-panels: 3.0.6
    shiki: 3.20.0
    shiki-magic-move: 1.2.1
    storybook: 10.1.11
    styled-components: 6.1.19
    swc-loader: 0.2.6
    tailwindcss: 4.1.16
    tree-kill: 1.2.2
    tsup: 8.5.0
    tsx: 4.21.0
    typescript: 5.9.3
    unionfs: 4.6.0
    vite: 7.3.0
    vitest: 4.0.5
    wasm-pack: 0.13.1
    webpack: 5.102.1
