packages:
  - packages/*
catalogs:
  core:
    "@babel/core": 7.23.2
    "@babel/plugin-syntax-typescript": 7.22.5
    "@swc/counter": 0.1.3

  dev:
    "@babel/preset-typescript": 7.26.0
    "@babel/types": 7.23.0
    "@changesets/cli": 2.27.9
    "@codspeed/benchmark.js-plugin": 3.1.0
    "@monaco-editor/react": 4.6.0
    "@next/mdx": 15.0.2
    "@shikijs/monaco": 1.22.2
    "@shikijs/transformers": 1.22.2
    "@swc/core": 1.7.42
    "@testing-library/dom": 10.4.0
    "@testing-library/jest-dom": 5.17.0
    "@testing-library/react": 16.1.0
    "@types/babel__core": 7.1.14
    "@types/benchmark": 2.1.5
    "@types/jest": 29.5.12
    "@types/mdx": 2.0.13
    "@types/node": 22.9.0
    "@types/react": 19.0.2
    "@types/react-dom": 19.0.2
    "@types/webpack": 5.28.5
    "@vitejs/plugin-react": 4.3.1
    autoprefixer: 10.4.20
    benchmark: 2.1.4
    fast-glob: 3.3.2
    fumadocs-core: 14.5.6
    fumadocs-mdx: 11.1.2
    fumadocs-openapi: 5.8.1
    fumadocs-twoslash: 2.0.1
    fumadocs-ui: 14.5.6
    jest: 29.6.2
    jest-environment-jsdom: 29.6.2
    jsdom: 25.0.1
    memfs: 4.9.3
    next: 15.0.4
    next-themes: 0.4.3
    postcss: 8.4.47
    postcss-nested: 6.2.0
    prettier: 3.0.3
    raw-loader: 4.0.2
    react: 19.0.0
    react-dom: 19.0.0
    react-resizable-panels: 2.1.6
    shiki: 1.22.2
    styled-components: 6.1.1
    swc-loader: 0.2.6
    tailwindcss: 3.4.14
    tree-kill: 1.2.2
    tsup: 7.2.0
    typescript: 5.5.2
    unionfs: 4.5.4
    vite: 5.3.4
    vitest: 2.0.4
    webpack: 5.92.1
