packages:
  - packages/*
  - examples/*
  - benchmarks
  - cross-file-tests
  - docs

catalogs:
  core:
    "@babel/parser": ^7.28.6
    "@babel/traverse": ^7.28.6
    "@swc/core": 1.15.11
    "@swc/counter": 0.1.3
  dev:
    "@babel/preset-typescript": 7.28.5
    "@changesets/cli": 2.29.8
    "@codspeed/benchmark.js-plugin": 5.0.1
    "@eslint/eslintrc": 3.3.3
    "@monaco-editor/react": 4.7.0
    "@next/eslint-plugin-next": 16.1.6
    "@next/mdx": 16.1.6
    "@radix-ui/react-switch": 1.2.6
    "@shikijs/monaco": 3.21.0
    "@shikijs/transformers": 3.21.0
    "@storybook/addon-docs": 10.2.3
    "@storybook/addon-webpack5-compiler-swc": 4.0.2
    "@storybook/react": 10.2.3
    "@storybook/react-vite": 10.2.3
    "@storybook/react-webpack5": 10.2.3
    "@swc/helpers": 0.5.18
    "@tailwindcss/postcss": 4.1.18
    "@testing-library/dom": 10.4.1
    "@testing-library/jest-dom": 6.9.1
    "@testing-library/react": 16.3.2
    "@types/babel__core": 7.20.5
    "@types/babel__traverse": 7.28.0
    "@types/benchmark": 2.1.5
    "@types/jest": 30.0.0
    "@types/mdx": 2.0.13
    "@types/node": 25.1.0
    "@types/react": 19.2.10
    "@types/react-dom": 19.2.3
    "@types/webpack": 5.28.5
    "@typescript-eslint/rule-tester": 8.54.0
    "@typescript-eslint/utils": 8.54.0
    "@vitejs/plugin-react": 5.1.2
    "@vitejs/plugin-react-swc": 4.2.2
    autoprefixer: 10.4.23
    benchmark: 2.1.4
    eslint: 9.39.2
    eslint-config-next: 16.1.6
    eslint-doc-generator: 3.0.2
    fast-glob: 3.3.3
    fflate: 0.8.2
    fumadocs-core: 16.4.11
    fumadocs-mdx: 14.2.6
    fumadocs-twoslash: 3.1.12
    fumadocs-ui: 16.4.11
    jest: 30.2.0
    jest-environment-jsdom: 30.2.0
    js-base64: 3.7.8
    jsdom: 27.4.0
    lz-string: 1.5.0
    memfs: 4.56.10
    next: 16.1.6
    next-themes: 0.4.6
    postcss: 8.5.6
    postcss-nested: 7.0.2
    prettier: 3.8.1
    raw-loader: 4.0.2
    react: 19.2.4
    react-dom: 19.2.4
    react-resizable-panels: 4.5.6
    shiki: 3.21.0
    shiki-magic-move: 1.2.1
    storybook: 10.2.3
    styled-components: 6.3.8
    swc-loader: 0.2.7
    tailwindcss: 4.1.18
    tree-kill: 1.2.2
    tsup: 8.5.1
    tsx: 4.21.0
    typescript: 5.9.3
    unionfs: 4.6.0
    vite: 7.3.1
    vitest: 4.0.18
    wasm-pack: 0.14.0
    webpack: 5.104.1
