[package]
name = "playground-wasm"
version = "0.1.0"
edition = "2024"
workspace = "../../yak-swc"

[lib]
crate-type = ["cdylib"]

[features]
# required by the swc macros; should not be enabled
__plugin = []

[dependencies]
anyhow = "1.0.98"
console_error_panic_hook = "0.1.7"
js-sys = "0.3.77"
serde = { version = "1.0.219", features = ["derive"] }
serde-wasm-bindgen = {version = "0.6.5"}
# enable the js flag for the getrandom transitive dependency
getrandom = { version = "*", features = ["wasm_js"] }
swc_core = { workspace = true, features = [
    "ecma_ast_serde",
    "binding_macro_wasm",
] }
wasm-bindgen = "0.2"
yak_swc = { version = "0.1.0", path = "../../yak-swc/yak_swc", default-features = false }
either = "1.15.0"
tsify = "0.5.5"

[dev-dependencies]
wasm-bindgen-test = "0.3.50"
