[package]
name = "yak_swc"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["plugin"]
plugin = ["swc_core/ecma_plugin_transform"]

[dependencies]
lazy_static.workspace = true
serde.workspace = true
serde_json.workspace = true
swc_core = { workspace = true, features = ["common", "ecma_ast", "ecma_visit"]}
css_in_js_parser = { path = "../css_in_js_parser" }
relative_posix_path = { path = "../relative_posix_path" }
itertools.workspace = true
percent-encoding.workspace = true
rustc-hash.workspace = true

[dev-dependencies]
divan.workspace = true
regex.workspace = true
swc_ecma_transforms_testing.workspace = true
swc_ecma_parser.workspace = true
testing.workspace = true
swc_core = { workspace = true, features = ["ecma_transforms", "testing_transform"]}

[[bench]]
name = "extension_detection"
harness = false

# .cargo/config defines few alias to build plugin.
# cargo build-wasi generates wasm-wasi32 binary
# cargo build-wasm32 generates wasm32-unknown-unknown binary.
