[package]
name = "yak_swc"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
lazy_static = "1.4.0"
serde = "1.0.203"
serde_json = "1.0.120"
swc_core = { version = "0.99.3", features = ["ecma_plugin_transform"] }
css_in_js_parser = { path = "../css_in_js_parser" }
relative_posix_path = { path = "../relative_posix_path" }
itertools = "0.13.0"
percent-encoding = "2.3.1"
rustc-hash = "2.0.0"

[dev-dependencies]
swc = "0.282.2"
swc_ecma_transforms_testing = "0.146.1"
testing = "0.36.0"

# .cargo/config defines few alias to build plugin.
# cargo build-wasi generates wasm-wasi32 binary
# cargo build-wasm32 generates wasm32-unknown-unknown binary.
