// @ts-nocheck -- skip type checking
import * as docs_9 from "../content/docs/why-next-yak.mdx?collection=docs&hash=1762184783598"
import * as docs_8 from "../content/docs/roadmap.mdx?collection=docs&hash=1762184783598"
import * as docs_7 from "../content/docs/migration-from-styled-components.mdx?collection=docs&hash=1762184783598"
import * as docs_6 from "../content/docs/how-does-it-work.mdx?collection=docs&hash=1762184783598"
import * as docs_5 from "../content/docs/getting-started.mdx?collection=docs&hash=1762184783598"
import * as docs_4 from "../content/docs/features.mdx?collection=docs&hash=1762184783598"
import * as docs_3 from "../content/docs/faq.mdx?collection=docs&hash=1762184783598"
import * as docs_2 from "../content/docs/examples.mdx?collection=docs&hash=1762184783598"
import * as docs_1 from "../content/docs/eslint-plugin.mdx?collection=docs&hash=1762184783598"
import * as docs_0 from "../content/docs/comparison.mdx?collection=docs&hash=1762184783598"
import { _runtime } from "fumadocs-mdx"
import * as _source from "../source.config"
export const docs = _runtime.docs<typeof _source.docs>([{ info: {"path":"comparison.mdx","absolutePath":"/Users/luca/personal/next-yak/docs/content/docs/comparison.mdx"}, data: docs_0 }, { info: {"path":"eslint-plugin.mdx","absolutePath":"/Users/luca/personal/next-yak/docs/content/docs/eslint-plugin.mdx"}, data: docs_1 }, { info: {"path":"examples.mdx","absolutePath":"/Users/luca/personal/next-yak/docs/content/docs/examples.mdx"}, data: docs_2 }, { info: {"path":"faq.mdx","absolutePath":"/Users/luca/personal/next-yak/docs/content/docs/faq.mdx"}, data: docs_3 }, { info: {"path":"features.mdx","absolutePath":"/Users/luca/personal/next-yak/docs/content/docs/features.mdx"}, data: docs_4 }, { info: {"path":"getting-started.mdx","absolutePath":"/Users/luca/personal/next-yak/docs/content/docs/getting-started.mdx"}, data: docs_5 }, { info: {"path":"how-does-it-work.mdx","absolutePath":"/Users/luca/personal/next-yak/docs/content/docs/how-does-it-work.mdx"}, data: docs_6 }, { info: {"path":"migration-from-styled-components.mdx","absolutePath":"/Users/luca/personal/next-yak/docs/content/docs/migration-from-styled-components.mdx"}, data: docs_7 }, { info: {"path":"roadmap.mdx","absolutePath":"/Users/luca/personal/next-yak/docs/content/docs/roadmap.mdx"}, data: docs_8 }, { info: {"path":"why-next-yak.mdx","absolutePath":"/Users/luca/personal/next-yak/docs/content/docs/why-next-yak.mdx"}, data: docs_9 }], [{"info":{"path":"meta.json","absolutePath":"/Users/luca/personal/next-yak/docs/content/docs/meta.json"},"data":{"title":"ui","pages":["---Guide---","index","getting-started","migration-from-styled-components","eslint-plugin","faq","---Details---","why-next-yak","features","how-does-it-work","comparison","examples","roadmap","---Links---","[Next-Yak](https://github.com/jantimon/next-yak)"],"root":true}}])