import { loader } from "fumadocs-core/source";
// Generated by fumadocs-mdx at the project root (see `.source/`).
import { blog as posts } from "../../.source/server";

export const blog = loader({
  baseUrl: "/blog",
  source: posts.toFumadocsSource(),
});
