import { loader } from "fumadocs-core/source";
// Generated by fumadocs-mdx at the project root (see `.source/`).
import { docs } from "../../.source/server";

export const source = loader({
  baseUrl: "/documentation",
  source: docs.toFumadocsSource(),
});
