import { styled } from "./styled.js";
import type { HtmlTags, LiteralWithAttrs } from "./publicStyledApi.js";
import type { QwikJSX } from "@qwik.dev/core";

// each export carries its type in writing: the declaration build cannot name
// qwik's element attribute interfaces (they leave core's public entry only
// through QwikJSX.IntrinsicElements)
type StyledTag<T extends HtmlTags> = LiteralWithAttrs<QwikJSX.IntrinsicElements[T]>;
/// Internal API to create styled components
/// Optimization for faster rendering and smaller bundle size in production
/// thanks to better minification and dead code elimination
///
/// List taken from https://github.com/styled-components/styled-components/blob/e0019ba666fab4b5aaa2bff71ba6ad0005a299fd/packages/styled-components/src/utils/domElements.ts#L90
export const __yak_a: StyledTag<"a"> = /*#__PURE__*/ styled("a");
export const __yak_abbr: StyledTag<"abbr"> = /*#__PURE__*/ styled("abbr");
export const __yak_address: StyledTag<"address"> = /*#__PURE__*/ styled("address");
export const __yak_area: StyledTag<"area"> = /*#__PURE__*/ styled("area");
export const __yak_article: StyledTag<"article"> = /*#__PURE__*/ styled("article");
export const __yak_aside: StyledTag<"aside"> = /*#__PURE__*/ styled("aside");
export const __yak_audio: StyledTag<"audio"> = /*#__PURE__*/ styled("audio");
export const __yak_b: StyledTag<"b"> = /*#__PURE__*/ styled("b");
export const __yak_base: StyledTag<"base"> = /*#__PURE__*/ styled("base");
export const __yak_bdi: StyledTag<"bdi"> = /*#__PURE__*/ styled("bdi");
export const __yak_bdo: StyledTag<"bdo"> = /*#__PURE__*/ styled("bdo");
export const __yak_big: StyledTag<"span"> = /*#__PURE__*/ styled("big" as HtmlTags);
export const __yak_blockquote: StyledTag<"blockquote"> = /*#__PURE__*/ styled("blockquote");
export const __yak_body: StyledTag<"body"> = /*#__PURE__*/ styled("body");
export const __yak_br: StyledTag<"br"> = /*#__PURE__*/ styled("br");
export const __yak_button: StyledTag<"button"> = /*#__PURE__*/ styled("button");
export const __yak_canvas: StyledTag<"canvas"> = /*#__PURE__*/ styled("canvas");
export const __yak_caption: StyledTag<"caption"> = /*#__PURE__*/ styled("caption");
export const __yak_cite: StyledTag<"cite"> = /*#__PURE__*/ styled("cite");
export const __yak_code: StyledTag<"code"> = /*#__PURE__*/ styled("code");
export const __yak_col: StyledTag<"col"> = /*#__PURE__*/ styled("col");
export const __yak_colgroup: StyledTag<"colgroup"> = /*#__PURE__*/ styled("colgroup");
export const __yak_data: StyledTag<"data"> = /*#__PURE__*/ styled("data");
export const __yak_datalist: StyledTag<"datalist"> = /*#__PURE__*/ styled("datalist");
export const __yak_dd: StyledTag<"dd"> = /*#__PURE__*/ styled("dd");
export const __yak_del: StyledTag<"del"> = /*#__PURE__*/ styled("del");
export const __yak_details: StyledTag<"details"> = /*#__PURE__*/ styled("details");
export const __yak_dfn: StyledTag<"dfn"> = /*#__PURE__*/ styled("dfn");
export const __yak_dialog: StyledTag<"dialog"> = /*#__PURE__*/ styled("dialog");
export const __yak_div: StyledTag<"div"> = /*#__PURE__*/ styled("div");
export const __yak_dl: StyledTag<"dl"> = /*#__PURE__*/ styled("dl");
export const __yak_dt: StyledTag<"dt"> = /*#__PURE__*/ styled("dt");
export const __yak_em: StyledTag<"em"> = /*#__PURE__*/ styled("em");
export const __yak_embed: StyledTag<"embed"> = /*#__PURE__*/ styled("embed");
export const __yak_fieldset: StyledTag<"fieldset"> = /*#__PURE__*/ styled("fieldset");
export const __yak_figcaption: StyledTag<"figcaption"> = /*#__PURE__*/ styled("figcaption");
export const __yak_figure: StyledTag<"figure"> = /*#__PURE__*/ styled("figure");
export const __yak_footer: StyledTag<"footer"> = /*#__PURE__*/ styled("footer");
export const __yak_form: StyledTag<"form"> = /*#__PURE__*/ styled("form");
export const __yak_h1: StyledTag<"h1"> = /*#__PURE__*/ styled("h1");
export const __yak_h2: StyledTag<"h2"> = /*#__PURE__*/ styled("h2");
export const __yak_h3: StyledTag<"h3"> = /*#__PURE__*/ styled("h3");
export const __yak_h4: StyledTag<"h4"> = /*#__PURE__*/ styled("h4");
export const __yak_h5: StyledTag<"h5"> = /*#__PURE__*/ styled("h5");
export const __yak_h6: StyledTag<"h6"> = /*#__PURE__*/ styled("h6");
export const __yak_header: StyledTag<"header"> = /*#__PURE__*/ styled("header");
export const __yak_hgroup: StyledTag<"hgroup"> = /*#__PURE__*/ styled("hgroup");
export const __yak_hr: StyledTag<"hr"> = /*#__PURE__*/ styled("hr");
export const __yak_html: StyledTag<"html"> = /*#__PURE__*/ styled("html");
export const __yak_i: StyledTag<"i"> = /*#__PURE__*/ styled("i");
export const __yak_iframe: StyledTag<"iframe"> = /*#__PURE__*/ styled("iframe");
export const __yak_img: StyledTag<"img"> = /*#__PURE__*/ styled("img");
export const __yak_input: StyledTag<"input"> = /*#__PURE__*/ styled("input");
export const __yak_ins: StyledTag<"ins"> = /*#__PURE__*/ styled("ins");
export const __yak_kbd: StyledTag<"kbd"> = /*#__PURE__*/ styled("kbd");
export const __yak_keygen: StyledTag<"span"> = /*#__PURE__*/ styled("keygen" as HtmlTags);
export const __yak_label: StyledTag<"label"> = /*#__PURE__*/ styled("label");
export const __yak_legend: StyledTag<"legend"> = /*#__PURE__*/ styled("legend");
export const __yak_li: StyledTag<"li"> = /*#__PURE__*/ styled("li");
export const __yak_link: StyledTag<"link"> = /*#__PURE__*/ styled("link");
export const __yak_main: StyledTag<"main"> = /*#__PURE__*/ styled("main");
export const __yak_map: StyledTag<"map"> = /*#__PURE__*/ styled("map");
export const __yak_mark: StyledTag<"mark"> = /*#__PURE__*/ styled("mark");
export const __yak_menu: StyledTag<"menu"> = /*#__PURE__*/ styled("menu");
export const __yak_menuitem: StyledTag<"span"> = /*#__PURE__*/ styled("menuitem" as HtmlTags);
export const __yak_meta: StyledTag<"meta"> = /*#__PURE__*/ styled("meta");
export const __yak_meter: StyledTag<"meter"> = /*#__PURE__*/ styled("meter");
export const __yak_nav: StyledTag<"nav"> = /*#__PURE__*/ styled("nav");
export const __yak_noscript: StyledTag<"noscript"> = /*#__PURE__*/ styled("noscript");
export const __yak_object: StyledTag<"object"> = /*#__PURE__*/ styled("object");
export const __yak_ol: StyledTag<"ol"> = /*#__PURE__*/ styled("ol");
export const __yak_optgroup: StyledTag<"optgroup"> = /*#__PURE__*/ styled("optgroup");
export const __yak_option: StyledTag<"option"> = /*#__PURE__*/ styled("option");
export const __yak_output: StyledTag<"output"> = /*#__PURE__*/ styled("output");
export const __yak_p: StyledTag<"p"> = /*#__PURE__*/ styled("p");
export const __yak_param: StyledTag<"span"> = /*#__PURE__*/ styled("param" as HtmlTags);
export const __yak_picture: StyledTag<"picture"> = /*#__PURE__*/ styled("picture");
export const __yak_pre: StyledTag<"pre"> = /*#__PURE__*/ styled("pre");
export const __yak_progress: StyledTag<"progress"> = /*#__PURE__*/ styled("progress");
export const __yak_q: StyledTag<"q"> = /*#__PURE__*/ styled("q");
export const __yak_rp: StyledTag<"rp"> = /*#__PURE__*/ styled("rp");
export const __yak_rt: StyledTag<"rt"> = /*#__PURE__*/ styled("rt");
export const __yak_ruby: StyledTag<"ruby"> = /*#__PURE__*/ styled("ruby");
export const __yak_s: StyledTag<"s"> = /*#__PURE__*/ styled("s");
export const __yak_samp: StyledTag<"samp"> = /*#__PURE__*/ styled("samp");
export const __yak_script: StyledTag<"script"> = /*#__PURE__*/ styled("script");
export const __yak_section: StyledTag<"section"> = /*#__PURE__*/ styled("section");
export const __yak_select: StyledTag<"select"> = /*#__PURE__*/ styled("select");
export const __yak_small: StyledTag<"small"> = /*#__PURE__*/ styled("small");
export const __yak_source: StyledTag<"source"> = /*#__PURE__*/ styled("source");
export const __yak_span: StyledTag<"span"> = /*#__PURE__*/ styled("span");
export const __yak_strong: StyledTag<"strong"> = /*#__PURE__*/ styled("strong");
export const __yak_style: StyledTag<"style"> = /*#__PURE__*/ styled("style");
export const __yak_sub: StyledTag<"sub"> = /*#__PURE__*/ styled("sub");
export const __yak_summary: StyledTag<"summary"> = /*#__PURE__*/ styled("summary");
export const __yak_sup: StyledTag<"sup"> = /*#__PURE__*/ styled("sup");
export const __yak_table: StyledTag<"table"> = /*#__PURE__*/ styled("table");
export const __yak_tbody: StyledTag<"tbody"> = /*#__PURE__*/ styled("tbody");
export const __yak_td: StyledTag<"td"> = /*#__PURE__*/ styled("td");
export const __yak_textarea: StyledTag<"textarea"> = /*#__PURE__*/ styled("textarea");
export const __yak_tfoot: StyledTag<"tfoot"> = /*#__PURE__*/ styled("tfoot");
export const __yak_th: StyledTag<"th"> = /*#__PURE__*/ styled("th");
export const __yak_thead: StyledTag<"thead"> = /*#__PURE__*/ styled("thead");
export const __yak_time: StyledTag<"time"> = /*#__PURE__*/ styled("time");
export const __yak_tr: StyledTag<"tr"> = /*#__PURE__*/ styled("tr");
export const __yak_track: StyledTag<"track"> = /*#__PURE__*/ styled("track");
export const __yak_u: StyledTag<"u"> = /*#__PURE__*/ styled("u");
export const __yak_ul: StyledTag<"ul"> = /*#__PURE__*/ styled("ul");
export const __yak_use: StyledTag<"use"> = /*#__PURE__*/ styled("use");
export const __yak_var: StyledTag<"var"> = /*#__PURE__*/ styled("var");
export const __yak_video: StyledTag<"video"> = /*#__PURE__*/ styled("video");
export const __yak_wbr: StyledTag<"wbr"> = /*#__PURE__*/ styled("wbr");
export const __yak_circle: StyledTag<"circle"> = /*#__PURE__*/ styled("circle");
export const __yak_clipPath: StyledTag<"clipPath"> = /*#__PURE__*/ styled("clipPath");
export const __yak_defs: StyledTag<"defs"> = /*#__PURE__*/ styled("defs");
export const __yak_ellipse: StyledTag<"ellipse"> = /*#__PURE__*/ styled("ellipse");
export const __yak_foreignObject: StyledTag<"foreignObject"> =
  /*#__PURE__*/ styled("foreignObject");
export const __yak_g: StyledTag<"g"> = /*#__PURE__*/ styled("g");
export const __yak_image: StyledTag<"image"> = /*#__PURE__*/ styled("image");
export const __yak_line: StyledTag<"line"> = /*#__PURE__*/ styled("line");
export const __yak_linearGradient: StyledTag<"linearGradient"> =
  /*#__PURE__*/ styled("linearGradient");
export const __yak_marker: StyledTag<"marker"> = /*#__PURE__*/ styled("marker");
export const __yak_mask: StyledTag<"mask"> = /*#__PURE__*/ styled("mask");
export const __yak_path: StyledTag<"path"> = /*#__PURE__*/ styled("path");
export const __yak_pattern: StyledTag<"pattern"> = /*#__PURE__*/ styled("pattern");
export const __yak_polygon: StyledTag<"polygon"> = /*#__PURE__*/ styled("polygon");
export const __yak_polyline: StyledTag<"polyline"> = /*#__PURE__*/ styled("polyline");
export const __yak_radialGradient: StyledTag<"radialGradient"> =
  /*#__PURE__*/ styled("radialGradient");
export const __yak_rect: StyledTag<"rect"> = /*#__PURE__*/ styled("rect");
export const __yak_stop: StyledTag<"stop"> = /*#__PURE__*/ styled("stop");
export const __yak_svg: StyledTag<"svg"> = /*#__PURE__*/ styled("svg");
export const __yak_text: StyledTag<"text"> = /*#__PURE__*/ styled("text");
export const __yak_tspan: StyledTag<"tspan"> = /*#__PURE__*/ styled("tspan");
