[package]
name = "css_in_js_parser"
version = "0.1.0"
edition = "2021"
authors = ["Jan Nicklas <j.nicklas@me.com>"]
description = "A CSS-in-JS parser that maintains parsing state for dynamic CSS processing"
repository = "https://github.com/jantimon/next-yak"
license = "MIT"
keywords = ["css", "parser", "css-in-js"]
categories = ["parser-implementations", "web-programming"]

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
serde_repr.workspace = true

[dev-dependencies]
insta.workspace = true
