name: autofix.ci - Apply Changes
on:
  workflow_run:
    workflows: ["autofix.ci"]
    types:
      - completed

permissions:
  contents: write
  pull-requests: write

jobs:
  apply-autofix:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'pull_request' }}
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: autofix.yml
          run_id: ${{ github.event.workflow_run.id }}
          name: formatted-files
          if_no_artifact_found: warn

      - name: Get PR info
        uses: actions/github-script@v7
        id: pr-info
        with:
          script: |
            const { owner, repo } = context.repo;
            const run = await github.rest.actions.getWorkflowRun({
              owner,
              repo,
              run_id: context.payload.workflow_run.id
            });

            if (run.data.event !== 'pull_request') {
              return { number: null, head_sha: null };
            }

            const pulls = await github.rest.pulls.list({
              owner,
              repo,
              head: run.data.head_branch,
              state: 'open'
            });

            if (pulls.data.length === 0) {
              return { number: null, head_sha: null };
            }

            return {
              number: pulls.data[0].number,
              head_sha: run.data.head_sha
            };

      - name: Checkout PR
        if: steps.pr-info.outputs.result != '{"number":null,"head_sha":null}'
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.event.workflow_run.head_repository.full_name }}
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Apply changes
        if: steps.pr-info.outputs.result != '{"number":null,"head_sha":null}'
        uses: autofix-ci/action@635ffb0c9798bd160680f18fd73371e355b85f27
