name: Deploy packages/docs
env:
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_DOCS_PROJECT_ID }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}

on:
  workflow_run:
    workflows: ["Build packages/docs"]
    types:
      - completed

permissions:
  contents: read
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download build artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: docs.yml
          run_id: ${{ github.event.workflow_run.id }}
          name: docs-build

      - name: Download PR info
        if: ${{ github.event.workflow_run.event == 'pull_request' }}
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: docs.yml
          run_id: ${{ github.event.workflow_run.id }}
          name: pr-info
          if_no_artifact_found: warn

      - name: Install Vercel CLI
        run: npm install -g vercel@35

      - name: Link Vercel project
        run: |
          cd packages/docs
          vercel link --yes --token ${{ secrets.VERCEL_TOKEN }}

      # Preview deployment (for pull requests and non-main pushes)
      - name: Pull Vercel environment information (Preview)
        if: ${{ github.event.workflow_run.event == 'pull_request' || (github.event.workflow_run.event == 'push' && github.event.workflow_run.head_branch != 'main') }}
        run: |
          cd packages/docs
          vercel pull --yes --environment=preview --token ${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel (Preview)
        id: deploy-preview
        if: ${{ github.event.workflow_run.event == 'pull_request' || (github.event.workflow_run.event == 'push' && github.event.workflow_run.head_branch != 'main') }}
        run: |
          cd packages/docs
          DEPLOYMENT_URL=$(vercel deploy --prebuilt --token ${{ secrets.VERCEL_TOKEN }})
          echo "deployment_url=$DEPLOYMENT_URL" >> $GITHUB_OUTPUT

      - name: Read PR number
        id: pr-number
        if: ${{ github.event.workflow_run.event == 'pull_request' }}
        run: |
          if [ -f pr-number.txt ]; then
            PR_NUMBER=$(cat pr-number.txt)
            echo "number=$PR_NUMBER" >> $GITHUB_OUTPUT
          fi

      - name: Find Documentation Comment
        uses: peter-evans/find-comment@v3
        id: find-comment
        if: ${{ steps.pr-number.outputs.number }}
        with:
          issue-number: ${{ steps.pr-number.outputs.number }}
          comment-author: "github-actions[bot]"
          body-includes: "📚 Documentation Preview Deployed!"

      - name: Create or Update Documentation Comment
        if: ${{ steps.pr-number.outputs.number }}
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ steps.pr-number.outputs.number }}
          body: |
            ## 📚 Documentation Preview Deployed!

            A preview of the documentation changes in this PR has been deployed to Vercel:

            🔗 [View Documentation Preview](${{ steps.deploy-preview.outputs.deployment_url }})

            This preview will update automatically with new commits to this PR.
          edit-mode: replace

      # Production deployment (for main branch pushes)
      - name: Pull Vercel environment information (Production)
        if: ${{ github.event.workflow_run.event == 'push' && github.event.workflow_run.head_branch == 'main' }}
        run: |
          cd packages/docs
          vercel pull --yes --environment=production --token ${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel (Production)
        if: ${{ github.event.workflow_run.event == 'push' && github.event.workflow_run.head_branch == 'main' }}
        run: |
          cd packages/docs
          vercel deploy --prebuilt --prod --token ${{ secrets.VERCEL_TOKEN }}
