name: Build packages/example
on:
  push:
    branches:
      - main
    paths:
      - "packages/example/**"
      - "packages/yak-swc/**"
      - "packages/next-yak/**"
      - ".github/workflows/example.yml"
  pull_request:
    branches:
      - main
    paths:
      - "packages/example/**"
      - "packages/yak-swc/**"
      - "packages/next-yak/**"
      - ".github/workflows/example.yml"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10.15.0
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install node_modules
        run: pnpm install

      - name: Build Linter
        run: pnpm --filter eslint-plugin-yak build

      - name: Lint Example
        run: pnpm --filter next-yak-example lint

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-wasip1

      - name: Enable caching
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: packages/yak-swc

      - name: Build with SWC
        run: pnpm run build:swc

      - name: Build example
        run: cd packages/example && pnpm build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: example-build
          path: |
            packages/example/.next/
            packages/example/package.json
            packages/example/next.config.mjs
            packages/example/public/
          retention-days: 1

      - name: Save PR info
        if: github.event_name == 'pull_request'
        run: echo "${{ github.event.number }}" > pr-number.txt

      - name: Upload PR info
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: pr-info
          path: pr-number.txt
          retention-days: 1
