name: Build and Deploy packages/example

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 7

    - name: Install Vercel CLI
      run: npm install -g vercel

    - name: Build with SWC
      run: pnpm run build:swc

    - name: Link Vercel project
      run: vercel link --yes --token ${{ secrets.VERCEL_TOKEN }}

    - name: Pull Vercel environment information
      run: vercel pull --yes --token ${{ secrets.VERCEL_TOKEN }}

    - name: Build project artifacts
      run: vercel build --token ${{ secrets.VERCEL_TOKEN }}

    - name: Deploy to Vercel
      run: vercel deploy --prebuilt --token ${{ secrets.VERCEL_TOKEN }}