name: Build and Deploy examples/next-js

env:
  VERCEL_PROJECT_ID: ${{ vars.VERCEL_PROJECT_ID }}
  VERCEL_ORG_ID: ${{ vars.VERCEL_ORG_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

on:
  push:
    branches:
      - main
    paths:
      - "examples/next-js/**"
      - "packages/yak-swc/**"
      - "packages/next-yak/**"
      - ".github/workflows/example.yml"
  workflow_dispatch: # manual re-deploy of main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-and-deploy:
    name: Build and deploy example
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          persist-credentials: false

      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        name: Install pnpm
        with:
          version: 10.15.0
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install node_modules
        run: pnpm install

      - name: Build Linter
        run: pnpm --filter eslint-plugin-yak build

      - name: Lint Example
        run: pnpm --filter next-yak-example lint

      - name: Add Rust wasm targets
        run: rustup target add wasm32-wasip1 wasm32-unknown-unknown

      - name: Enable caching
        uses: Swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1 # v2.8.1
        with:
          workspaces: packages/yak-swc

      - name: Build with SWC
        run: pnpm run build:swc

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Link Vercel project
        run: vercel link --yes

      - name: Pull Vercel environment information
        run: vercel pull --yes --environment=production

      - name: Build project artifacts
        run: vercel build --prod

      - name: Deploy to Vercel
        run: |
          rm -rf .git # Remove the .git directory to avoid vercel to read the current author
          vercel deploy --prebuilt --prod
