name: Build and Deploy packages/example

on:
  push:
    branches-ignore:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Add wasm32-wasi target
      run: rustup target add wasm32-wasi

    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        version: 8.6.1
        run_install: false

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: 'pnpm'

    - name: Install node_modules
      run: pnpm install

    - name: Install Vercel CLI
      run: npm install -g vercel@34.3.0

    - name: Enable caching
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: packages/yak-swc

    - name: Build with SWC
      run: pnpm run build:swc

    - name: Link Vercel project
      run: vercel link --yes --token ${{ secrets.VERCEL_TOKEN }}

    - name: Pull Vercel environment information
      run: vercel pull --yes --environment=preview --token ${{ secrets.VERCEL_TOKEN }}

    - name: Pull Vercel environment information
      working-directory: packages/example
      run: vercel pull --yes --environment=preview --token ${{ secrets.VERCEL_TOKEN }}

    - name: Build project artifacts
      working-directory: packages/example
      run: vercel build --yes --token ${{ secrets.VERCEL_TOKEN }}

    - name: Deploy to Vercel
      working-directory: packages/example
      run: vercel deploy --prebuilt --token ${{ secrets.VERCEL_TOKEN }}