name: Vite-Tests

on:
  push:
    branches: [ "main" ]
    paths:
      - './package.json'
      - 'packages/next-yak/**'
      - 'packages/yak-swc/**'
      - '.github/workflows/node.js.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - './package.json'
      - 'packages/next-yak/**'
      - 'packages/yak-swc/**'
      - '.github/workflows/node.js.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 8.6.1
          run_install: false

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Add wasm32-wasi target
        run: rustup target add wasm32-wasi
      - name: Enable caching
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: packages/yak-swc
      - name: Build with SWC
        run: pnpm run build:swc    

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install
      
      - name: Build
        run: pnpm run build

      - name: Test
        run: pnpm run test