name: SWC validation
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  rust:
    name: Rust tests & lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@5d458579430fc14a04a08a1e7d3694f545e91ce6 # stable
        with:
          toolchain: stable
      - name: Enable caching
        uses: Swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1 # v2
        with:
          workspaces: packages/yak-swc
      - name: Run cargo check
        run: cargo check --manifest-path packages/yak-swc/Cargo.toml
      - name: Run cargo test
        run: cargo test --manifest-path packages/yak-swc/Cargo.toml
      - name: Run cargo fmt
        run: cargo fmt --manifest-path packages/yak-swc/Cargo.toml --all -- --check
      - name: Run cargo clippy
        run: cargo clippy --manifest-path packages/yak-swc/Cargo.toml
